version: "3.7"
services:
  corebase:
    build:
      context: ./base
      dockerfile: Dockerfile
      target: corebase
    image: "drudge:corebase"

  base:
    build:
      context: ./base
      dockerfile: Dockerfile
      target: base
    image: "drudge:base"

  drudge:
    build:
      context: ./drudge
      dockerfile: Dockerfile
    image: "drudge:drudge"
    # Service for developmental purpose.
    volumes:
      - type: bind
        source: ./drudge
        target: /home/src/drudge
      - type: bind
        source: ./work
        target: /home/work
    command: ["sleep", "infinity"]

  gristmill:
    build:
      context: ./gristmill
      dockerfile: Dockerfile
    image: "drudge:gristmill"
    volumes:
      - type: bind
        source: ./gristmill
        target: /home/src/gristmill
      - type: bind
        source: ./work
        target: /home/work
    command: ["sleep", "infinity"]
